// Generated by CoffeeScript 1.7.1

/*invokeService(url ->
    class client
        Titanium.Network.createHTTPClient()
        @setTimeout 10000
        @open 'GET', url
        @send
)
 */


/*
class ServiceConsumer

    yield (url, type='GET') on :client ->
        new Titanium.Network.createHTTPClient()
        setTimeout 10000
        open type, url
        send
 */

(function() {


}).call(this);
