// Generated by CoffeeScript 1.7.1
(function() {
  var addBookToCollection, books;

  addBookToCollection = function(model) {
    var book;
    if (model == null) {
      model = "books";
    }
    book = Alloy.createModel(model, {
      title: $.titleInput.value,
      author: $.authorInput.value
    });
    books.add(book);
    book.save();
    $.addbook.close();
  };

  books = Alloy.Collections.books;

}).call(this);
