// Generated by CoffeeScript 1.7.1
(function() {
  exports.definition = {
    config: {
      columns: {
        title: 'string',
        author: 'string'
      },
      adapter: {
        type: 'sql',
        collection_name: 'books'
      }
    }
  };

}).call(this);
